### ISSUE TITLE
errorMessage."parameter validation failed:\nInvalid type for parameter name:None , type: <class 'None Type'>,valid types:<class 'str'>",

### ISSUE THREAD

**Issue by rudra1921** [liavyona/lambda-eks-integration#2]
while testing lambda ... we are getting error. 

errorMessage."parameter validation failed:\nInvalid type for parameter name:None , type: <class 'None Type'>,valid types:<class 'str'>",
  "error type":"paramValidationError",
   "requestedID":-------",
     "StackTrace":[
       "File \"var/task/test.py\",line 192,in test\n cluser_info =
      _get_cluster_info(cluster_name,cluster_region)\n"
]

**Comment by liavyona** [comment]
Hi @rudra1921 

The error is related to lack of required environment variables. The function that throws the exception is AWS EKS describe_cluster. Please can you make sure you add all the required environment variables (which are listed at the README file?

**Comment by rudra1921** [comment]
HI...this is environment variables in my case....

CLUSTER_NAME_ENV = "eks"
CLUSTER_REGION_ENV = "ap-northeast-1"
SERVICE_NAMESPACE_ENV = "dev-nu"
SERVICE_NAME_ENV = "test-dev"
SERVICE_PORT_ENV = "44053"
SERVICE_REQUEST_TIMEOUT_ENV = "SERVICE_REQUEST_TIMEOUT"
SERVICE_REQUEST_METHOD_ENV = "SERVICE_REQUEST_METHOD"
SERVICE_REQUEST_PATH_ENV = "SERVICE_REQUEST_PATH"

**Comment by liavyona** [comment]
Can you add a screen shot of your kubernetes service? Also, this part is not valid:
SERVICE_REQUEST_TIMEOUT_ENV = "SERVICE_REQUEST_TIMEOUT"
SERVICE_REQUEST_METHOD_ENV = "SERVICE_REQUEST_METHOD"
SERVICE_REQUEST_PATH_ENV = "SERVICE_REQUEST_PATH"
I encourage you to read it https://liavyona09.medium.com/spice-up-your-kubernetes-environment-with-aws-lambda-a07d81347607 and try to see the gaps
